New f: 15
Clearing cache... (4.77519)
Cache cleared.
New f: 16
Clearing cache... (6.12299)
Cache cleared.
Clearing cache... (6.14813)
Cache cleared.
Clearing cache... (6.14813)
Cache cleared.
Clearing cache... (6.64921)
Cache cleared.
Clearing cache... (6.64921)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (6.84904)
Cache cleared.
Clearing cache... (7.30605)
Cache cleared.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
